SELECT COUNT(ID) FROM CITY WHERE POPULATION > 100000;

SELECT SUM(POPULATION) FROM CITY WHERE DISTRICT = 'California';

SELECT AVG(POPULATION) FROM CITY WHERE DISTRICT = 'California';

SELECT ROUND(AVG(POPULATION)) FROM CITY;

SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE = 'JPN';

SELECT (MAX(POPULATION) - MIN(POPULATION)) FROM CITY;

SELECT ROUND(SUM(LAT_N),2), ROUND(SUM(LONG_W),2) FROM STATION;

