SELECT COUNT(ID) FROM CITY WHERE POPULATION > 100000;

SELECT SUM(POPULATION) FROM CITY WHERE DISTRICT = 'California';

SELECT AVG(POPULATION) FROM CITY WHERE DISTRICT = 'California';

SELECT ROUND(AVG(POPULATION)) FROM CITY;

SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE = 'JPN';

SELECT (MAX(POPULATION) - MIN(POPULATION)) FROM CITY;

SELECT ROUND(SUM(LAT_N),2), ROUND(SUM(LONG_W),2) FROM STATION;

-- BETWEEN ... AND ... both inclusive

SELECT TRUNCATE(SUM(LAT_N),4) FROM STATION WHERE LAT_N > 38.7880 AND LAT_N < 137.2345; 

MYSQL:
SELECT TRUNCATE(MAX(LAT_N),4) FROM STATION WHERE LAT_N < 137.2345;
ORACLE:
SELECT TRUNC(MAX(LAT_N),4) FROM STATION WHERE LAT_N < 137.2345;


SELECT ROUND(LONG_W,4) FROM STATION WHERE LAT_N = (SELECT MAX(LAT_N) FROM STATION WHERE LAT_N < 137.2345);

SELECT ROUND(MIN(LAT_N),4) FROM STATION WHERE LAT_N > 38.7780;

SELECT ROUND(LONG_W, 4) FROM STATION WHERE LAT_N = (SELECT MIN(LAT_N) FROM STATION WHERE LAT_N > 38.7780);



